import type {ContentAIProvider} from './ContentAIProvider';
import type {ContentContext,ContentSuggestion,DraftQuestion,NuruDraft} from './types';
import {flagDuplicates} from './questionDuplicate';

const delay=()=>new Promise(resolve=>setTimeout(resolve,700));
const question=(id:string,text:string,type:DraftQuestion['questionType'],answer:string):DraftQuestion=>({id,question:text,questionType:type,answer,explanation:`A correct response shows the learner can apply the core idea.`,difficulty:'Grade 8'});
export class MockContentAIProvider implements ContentAIProvider {
 readonly name='mock';
 async suggestContentGaps(context:ContentContext){await delay();return context.contentFamily==='skills'?[cssSuggestion]:[algebraSuggestion]}
 async generateLessonDraft(context:ContentContext,suggestion:ContentSuggestion):Promise<NuruDraft>{await delay();const practice=[question('q1','A taxi charges KSh 200 plus KSh 50 per kilometre. The fare is KSh 600. How many kilometres were travelled?','numeric','8'),question('q2','A taxi charges KSh 200 plus KSh 50 per kilometre. The fare is KSh 600. How many kilometres were travelled?','numeric','8'),question('q3','True or false: checking an answer in context is part of solving a word problem.','true_false','True'),question('q4','What should you identify before writing an equation?','short_answer','The unknown quantity')];return {...baseDraft(context,suggestion),template:'academic',objectives:suggestion.objectives,sections:[{id:'s1',heading:'Concept explanation',body:'Word problems describe relationships using everyday language. Identify the unknown, represent it with a variable, and translate each relationship into an equation.'},{id:'s2',heading:'Worked example 1',body:'Amina has 3 more books than twice Juma’s amount. If Amina has 15 books, 2x + 3 = 15, so x = 6.'},{id:'s3',heading:'Worked example 2',body:'A fixed taxi fee and a per-kilometre charge can be represented as 200 + 50k = 600.'},{id:'s4',heading:'Common mistake',body:'Do not stop after finding a number. Substitute it into the original situation and label the answer.'},{id:'s5',heading:'Practice activity',body:'Translate each scenario first; solve only after a partner checks the equation.'},{id:'s6',heading:'Summary',body:'Define, translate, solve, and verify.'}],questions:flagDuplicates(practice,[]),quiz:await this.generateQuiz(context,5)} }
 async generateExamples(){await delay();return ['A phone plan combines a fixed charge with a usage charge.','A rectangle has a perimeter expressed using an unknown side.','A savings goal grows by the same amount each week.']}
 async generatePracticeQuestions(_context:ContentContext,count=8){await delay();return Array.from({length:count},(_,i)=>question(`practice-${i}`,`Practice scenario ${i+1}: translate the relationship into an equation and solve.`,i%2?'short_answer':'multiple_choice',`Sample answer ${i+1}`))}
 async generateQuiz(context:ContentContext,count=5){await delay();return Array.from({length:count},(_,i)=>question(`quiz-${i}`,`Mastery check ${i+1}: which equation represents the described relationship?`,'multiple_choice',`Option ${String.fromCharCode(65+i%4)}`))}
 async improveContent(_context:ContentContext,current:string,action:string){await delay();return {current,action,proposed:`${current} In simpler terms, name what you do not know, write the relationship as an equation, then check that the result makes sense.`}}
 async generateProject(context:ContentContext,suggestion:ContentSuggestion):Promise<NuruDraft>{await delay();return {...baseDraft(context,suggestion),template:'practical',objectives:suggestion.objectives,sections:[{id:'p1',heading:'Goal',body:'Style a personal homepage that communicates a clear visual identity.'},{id:'p2',heading:'Concept',body:'Use selectors, the cascade, spacing, colour, and type intentionally.'},{id:'p3',heading:'Demonstration',body:'Inspect a starter page and trace how three CSS rules affect it.'},{id:'p4',heading:'Hands-on activity',body:'Create a hero, profile card, and responsive interests section.'},{id:'p5',heading:'Success criteria',body:'Readable type, consistent spacing, accessible contrast, and a responsive layout.'},{id:'p6',heading:'Hints',body:'Start mobile-first and use custom properties for repeated colours.'},{id:'p7',heading:'Reflection',body:'Which design decision best represents you, and what would you improve next?'}],questions:[],quiz:[]}}
}
const baseDraft=(context:ContentContext,suggestion:ContentSuggestion):Omit<NuruDraft,'template'|'objectives'|'sections'|'questions'|'quiz'>=>({id:crypto.randomUUID(),generationRequestId:crypto.randomUUID(),title:suggestion.title.replace(/^Add /,''),status:'draft',scope:context.scope,schoolName:context.scope==='school'?'Greenfield Academy':undefined,sourceLabel:context.scope==='school'?'Learnova Global Content':undefined});
export const algebraSuggestion:ContentSuggestion={id:'algebra-word-problems',scope:'school',type:'missing_content',title:'Add Algebraic Word Problems',description:'Add an application-focused lesson after Two-Step Equations.',reason:'The topic sequence contains equation-solving lessons but no application-focused lesson.',priority:'high',placement:'Grade 8 Mathematics → Algebra → after Two-Step Equations',objectives:['Translate simple word problems into equations','Solve equations based on practical scenarios','Verify answers in context'],package:['1 lesson','3 worked examples','8 practice questions','1 mastery quiz'],status:'pending'};
export const cssSuggestion:ContentSuggestion={id:'css-mini-project',scope:'school',type:'project_opportunity',title:'Add CSS Mini Project',description:'Create a mini project where learners style a personal homepage.',reason:'CSS Foundations contains concept lessons but no project milestone.',priority:'medium',placement:'Web Creator → CSS Foundations → final milestone',objectives:['Apply CSS selectors and cascade','Create a responsive visual design','Reflect on design choices'],package:['1 project brief','1 demonstration','1 hands-on activity','Success criteria and reflection'],status:'pending'};
export const contentAIProvider:ContentAIProvider=new MockContentAIProvider();
