import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Plus,Search,Edit3,UserX} from 'lucide-react';
import {PageHeader,EmptyState} from '@/layouts/AppShell';
import {useAuth} from '@/auth/AuthContext';
import {academicService} from '@/services/academicService';
import {peopleService} from '@/services/peopleService';
import type {Grade,SchoolClass,StudentProfile,TeacherProfile,Subject} from '@/types';
const input='rounded-xl border border-ink-300 bg-white px-3 py-2 text-sm'; const button='inline-flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white';
function ErrorText({value}:{value:string}){return value?<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{value}</p>:null}

export function StudentsPage(){const [rows,setRows]=useState<StudentProfile[]>([]),[grades,setGrades]=useState<Grade[]>([]),[q,setQ]=useState(''),[grade,setGrade]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState('');const load=()=>peopleService.students().then(setRows).catch(e=>setError(e.message));useEffect(()=>{load();academicService.grades().then(setGrades).catch(()=>{})},[]);const filtered=useMemo(()=>rows.filter(x=>(!q||x.profiles?.display_name.toLowerCase().includes(q.toLowerCase()))&&(!grade||x.grade_id===grade)&&(!status||x.status===status)),[rows,q,grade,status]);return <><PageHeader title="Students" description="Manage basic learner records without exposing a public directory." action={<button className={button} title="Account provisioning requires a secure server function"><Plus size={16}/>Add student</button>}/><div className="surface mb-5 flex flex-wrap gap-3 p-4"><label className="flex items-center gap-2"><Search size={17}/><input className={input} placeholder="Search students" value={q} onChange={e=>setQ(e.target.value)}/></label><select className={input} value={grade} onChange={e=>setGrade(e.target.value)}><option value="">All grades</option>{grades.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>active</option><option>inactive</option><option>graduated</option></select></div><ErrorText value={error}/>{rows.length===0?<EmptyState title="No students have been added yet." body="Student sign-in accounts must be provisioned by a secure server function; service credentials are never exposed here." action={<button className={button}>Add first student</button>}/>:<div className="surface overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-ink-100"><tr>{['Name','Student number','Grade','Class','Status','Actions'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(s=><tr className="border-t border-ink-200" key={s.id}><td className="px-4 py-4 font-semibold">{s.profiles?.display_name}</td><td className="px-4">{s.student_number??'—'}</td><td className="px-4">{s.grades?.name}</td><td className="px-4">{s.classes?.name??'—'}</td><td className="px-4 capitalize">{s.status}</td><td className="px-4"><button title="Edit"><Edit3 size={17}/></button><button className="ml-3" title="Deactivate" onClick={()=>peopleService.updateStudent(s.id,{status:'inactive'}).then(load)}><UserX size={17}/></button></td></tr>)}</tbody></table></div>}</>}

export function TeachersPage(){const [rows,setRows]=useState<TeacherProfile[]>([]),[q,setQ]=useState('');useEffect(()=>{peopleService.teachers().then(setRows).catch(()=>setRows([]))},[]);const filtered=rows.filter(t=>!q||t.profiles?.display_name.toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Teachers" description="View teaching staff and their class assignments." action={<button className={button}><Plus size={16}/>Add teacher</button>}/><div className="surface mb-5 p-4"><input className={input} placeholder="Search teachers" value={q} onChange={e=>setQ(e.target.value)}/></div>{rows.length===0?<EmptyState title="No teachers have been added yet." body="Teacher auth accounts will be safely provisioned through a server-side function."/>:<div className="surface overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{['Name','Staff number','Assigned classes','Status'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(t=><tr className="border-t" key={t.id}><td className="p-4 font-semibold">{t.profiles?.display_name}</td><td>{t.staff_number??'—'}</td><td>{t.teacher_classes?.map(c=>c.classes?.name).join(', ')||'None'}</td><td className="capitalize">{t.profiles?.status}</td></tr>)}</tbody></table></div>}</>}

export function GradesPage(){const {school}=useAuth();const [rows,setRows]=useState<Grade[]>([]),[name,setName]=useState(''),[error,setError]=useState('');const load=()=>academicService.grades().then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);async function submit(e:FormEvent){e.preventDefault();if(!school)return;await academicService.saveGrade({school_id:school.id,name,display_order:rows.length});setName('');load()}return <><PageHeader title="Grades" description="Configure your school's grade structure and ordering."/><ErrorText value={error}/><form onSubmit={submit} className="surface mb-5 flex gap-3 p-4"><input className={`${input} flex-1`} placeholder="Grade name" value={name} onChange={e=>setName(e.target.value)} required/><button className={button}><Plus size={16}/>Add grade</button></form>{rows.length===0?<EmptyState title="No grades configured" body="Add the first grade in your school's own academic structure."/>:<div className="space-y-3">{rows.map((g,i)=><div className="surface flex items-center justify-between p-4" key={g.id}><div><b>{g.name}</b><p className="text-xs text-ink-500">Order {i+1} · {g.is_active?'Active':'Disabled'}</p></div><button onClick={()=>{const n=prompt('Rename grade',g.name);if(n)academicService.saveGrade({...g,name:n}).then(load)}}><Edit3 size={18}/></button></div>)}</div>}</>}

export function ClassesPage(){const {school}=useAuth();const [rows,setRows]=useState<SchoolClass[]>([]),[grades,setGrades]=useState<Grade[]>([]),[name,setName]=useState(''),[grade,setGrade]=useState('');const load=()=>academicService.classes().then(setRows);useEffect(()=>{load();academicService.grades().then(x=>{setGrades(x);setGrade(x[0]?.id??'')})},[]);async function submit(e:FormEvent){e.preventDefault();if(!school||!grade)return;await academicService.saveClass({school_id:school.id,grade_id:grade,name});setName('');load()}return <><PageHeader title="Classes" description="Organize learners by grade and class teacher."/><form onSubmit={submit} className="surface mb-5 flex flex-wrap gap-3 p-4"><select className={input} value={grade} onChange={e=>setGrade(e.target.value)}>{grades.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><input className={`${input} flex-1`} placeholder="Class name, e.g. Grade 8A" value={name} onChange={e=>setName(e.target.value)} required/><button className={button}>Create class</button></form>{rows.length===0?<EmptyState title="Create your first class to start organizing learners." body="Add a grade first, then create at least one class."/>:<div className="grid gap-4 md:grid-cols-2">{rows.map(c=><article className="surface p-5" key={c.id}><h2 className="font-bold">{c.name}</h2><p className="text-sm text-ink-500">{c.grades?.name} · {c.student_profiles?.[0]?.count??0} students</p></article>)}</div>}</>}

export function SubjectsPage(){const {school}=useAuth();const [rows,setRows]=useState<Subject[]>([]),[grades,setGrades]=useState<Grade[]>([]),[name,setName]=useState('');const load=()=>academicService.subjects().then(setRows);useEffect(()=>{load();academicService.grades().then(setGrades)},[]);async function submit(e:FormEvent){e.preventDefault();if(!school)return;await academicService.saveSubject({name,slug:name.toLowerCase().trim().replace(/\s+/g,'-'),school_id:school.id,is_global:false,status:'active'});setName('');load()}return <><PageHeader title="Subjects" description="Use global curriculum subjects or create school-specific subjects."/><form onSubmit={submit} className="surface mb-5 flex gap-3 p-4"><input className={`${input} flex-1`} value={name} onChange={e=>setName(e.target.value)} placeholder="New school subject" required/><button className={button}>Add subject</button></form>{rows.length===0?<EmptyState title="No subjects available" body="A platform administrator can publish global subjects, or you can add a school subject."/>:<div className="space-y-3">{rows.map(s=><div className="surface p-5" key={s.id}><div className="flex justify-between"><b>{s.name}</b><span className="rounded-full bg-brand-50 px-2 py-1 text-xs text-brand-800">{s.is_global?'Global':'School'}</span></div><div className="mt-3 flex flex-wrap gap-3">{grades.map(g=><label className="text-sm" key={g.id}><input type="checkbox" className="mr-2" onChange={e=>school&&academicService.assignSubject(school.id,g.id,s.id,e.target.checked)}/>{g.name}</label>)}</div></div>)}</div>}</>}
