import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,CheckCircle2,Lightbulb,Target} from 'lucide-react';
import {EmptyState,PageHeader} from '@/layouts/AppShell';
import {assessmentService,confidenceLabel,masteryLabel,type AnswerResult,type PracticeQuestion,type PracticeRecommendation,type SkillMastery} from '@/services/assessmentService';

function response(q:PracticeQuestion,value:string):Record<string,unknown>{if(q.question_type==='multiple_choice')return {option_id:value};if(q.question_type==='multiple_select')return {option_ids:value.split(',').filter(Boolean)};return {value:q.question_type==='numeric'?Number(value):value}}

export function PracticePage(){
 const [params,setParams]=useSearchParams(),[recommendations,setRecommendations]=useState<PracticeRecommendation[]>([]),[mastery,setMastery]=useState<SkillMastery[]>([]),[assignments,setAssignments]=useState<Awaited<ReturnType<typeof assessmentService.assignments>>>([]),[questions,setQuestions]=useState<PracticeQuestion[]>([]),[attempt,setAttempt]=useState(''),[index,setIndex]=useState(0),[value,setValue]=useState(''),[hint,setHint]=useState(false),[result,setResult]=useState<AnswerResult|null>(null),[complete,setComplete]=useState<{raw_score:number;percentage_score:number}|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);const started=useRef(Date.now());
 const load=useCallback(async()=>{setLoading(true);try{const [r,m,a]=await Promise.all([assessmentService.recommendations(),assessmentService.mastery(),assessmentService.assignments()]);setRecommendations(r);setMastery(m);setAssignments(a)}catch(e){setError(e instanceof Error?e.message:'Practice could not be loaded.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const begin=async(skillId:string,count=5)=>{setError(null);setComplete(null);try{const session=await assessmentService.start(skillId,count);setAttempt(session.attempt_id);setQuestions(session.questions);setIndex(0);setValue('');setResult(null);setHint(false);started.current=Date.now();setParams({skill:skillId})}catch(e){setError(e instanceof Error?e.message:'Practice could not start.')}};
 const submit=async()=>{if(value)try{setResult(await assessmentService.answer(attempt,questions[index].id,response(questions[index],value),hint,Math.round((Date.now()-started.current)/1000)))}catch(e){setError(e instanceof Error?e.message:'Your answer could not be saved.')}};
 const next=async()=>{if(index+1<questions.length){setIndex(index+1);setValue('');setResult(null);setHint(false);started.current=Date.now()}else try{setComplete(await assessmentService.complete(attempt));setQuestions([]);await load()}catch(e){setError(e instanceof Error?e.message:'Practice could not be completed.')}};
 const q=questions[index],current=mastery.find(m=>m.skill_id===params.get('skill'));
 if(q)return <><PageHeader eyebrow={`Question ${index+1} of ${questions.length}`} title="Focused practice" description="Take your time. Hints are learning tools, and every answer helps update your current understanding."/><div className="mx-auto max-w-3xl surface p-6 sm:p-9"><div className="flex justify-between text-sm"><span className="font-bold capitalize text-brand-700">{q.difficulty}</span><span>{index+1} / {questions.length}</span></div><div className="mt-3 h-2 rounded-full bg-ink-100"><div className="h-2 rounded-full bg-brand-600" style={{width:`${(index+1)/questions.length*100}%`}}/></div><h2 className="mt-7 text-xl font-bold leading-relaxed">{q.question_text}</h2>{q.options?.length?<div className="mt-5 grid gap-3">{q.options.map(o=><label key={o.id} className={`cursor-pointer rounded-xl border p-4 ${value===o.id?'border-brand-600 bg-brand-50':'border-ink-200'}`}><input disabled={!!result} className="mr-3" type="radio" name="answer" value={o.id} checked={value===o.id} onChange={e=>setValue(e.target.value)}/>{o.text}</label>)}</div>:<input disabled={!!result} value={value} onChange={e=>setValue(e.target.value)} className="mt-5 w-full rounded-xl border border-ink-300 p-4" inputMode={q.question_type==='numeric'?'decimal':undefined} placeholder="Type your answer"/>}{q.hint&&!hint&&!result&&<button className="mt-5 flex items-center gap-2 text-sm font-bold text-amber-700" onClick={()=>setHint(true)}><Lightbulb size={17}/>Show hint</button>}{hint&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><b>Hint:</b> {q.hint}</p>}{result?<div role="status" className={`mt-6 rounded-2xl p-5 ${result.is_correct?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-950'}`}><p className="flex items-center gap-2 text-lg font-bold">{result.is_correct&&<CheckCircle2 size={20}/>} {result.feedback}</p><p className="mt-2 text-sm leading-relaxed">{result.explanation}</p><button onClick={()=>void next()} className="mt-5 flex items-center gap-2 rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">{index+1===questions.length?'Complete practice':'Next question'}<ArrowRight size={17}/></button></div>:<button disabled={!value} onClick={()=>void submit()} className="mt-6 rounded-xl bg-brand-700 px-6 py-3 font-bold text-white disabled:opacity-40">Check answer</button>}</div></>;
 return <><PageHeader eyebrow="Learn · practice · improve" title="Practice" description="Build understanding one question at a time. Recommendations reflect current evidence, not permanent ability."/>{error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{complete&&<section className="mb-6 rounded-2xl bg-emerald-50 p-6"><CheckCircle2 className="text-emerald-700"/><h2 className="mt-2 text-xl font-bold">Practice complete</h2><p className="mt-1">Score: {complete.percentage_score}% · Your understanding has been updated.</p>{current&&<p className="mt-2 text-sm">Current understanding: <b>{masteryLabel(current)} — {Math.round(current.mastery_score)}%</b> · {confidenceLabel(current.confidence_score)} confidence</p>}</section>}<div className="grid gap-6 lg:grid-cols-2"><section className="surface p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><Target className="text-brand-600"/>Recommended Practice</h2>{recommendations.length?<div className="mt-4 space-y-3">{recommendations.map(r=><div className="rounded-xl bg-brand-50 p-4" key={r.id}><p className="font-bold">Practice {r.skills?.name??'recommended skill'}</p><p className="mt-1 text-sm text-ink-600">{r.reason}</p><p className="mt-2 text-xs font-semibold">Estimated: 10 minutes</p><button onClick={()=>void begin(r.skill_id)} className="mt-3 rounded-lg bg-brand-700 px-4 py-2 text-sm font-bold text-white">Practice Now</button></div>)}</div>:<EmptyState title={loading?'Loading practice…':'No current learning gaps'} body="Keep practising; recommendations appear after enough meaningful evidence."/>}</section><section className="surface p-6"><h2 className="text-lg font-bold">Assigned practice</h2>{assignments.length?<div className="mt-4 space-y-3">{assignments.map(a=><button onClick={()=>void begin(a.skill_id,a.question_count)} key={a.id} className="flex w-full items-center justify-between rounded-xl border p-4 text-left"><span><b>{a.skills?.name??'Skill practice'}</b><small className="block text-ink-500">{a.question_count} questions{a.due_at?` · Due ${new Date(a.due_at).toLocaleDateString()}`:''}</small></span><ArrowRight/></button>)}</div>:<p className="mt-3 text-sm text-ink-600">No active teacher assignments.</p>}<h2 className="mt-7 text-lg font-bold">Practice by skill</h2><div className="mt-3 space-y-2">{mastery.map(m=><button key={m.skill_id} onClick={()=>void begin(m.skill_id)} className="flex w-full items-center justify-between rounded-xl bg-ink-50 p-3 text-left"><span>{m.skills?.name??'Course skill'}<small className="block text-ink-500">{masteryLabel(m)} · {Math.round(m.mastery_score)}%</small></span><ArrowRight size={17}/></button>)}</div></section></div><Link to="/app/progress" className="mt-6 inline-flex items-center gap-2 font-bold text-brand-700">View understanding and practice history <ArrowRight size={17}/></Link></>;
}
