import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {canSubmit,milestoneProgress} from '../src/services/projectProgress.ts';
const migration=readFileSync(new URL('../supabase/migrations/202609040003_stage10_skills_lab.sql',import.meta.url),'utf8');
const routes=readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');
const edge=readFileSync(new URL('../supabase/functions/nuru-tutor/index.ts',import.meta.url),'utf8');
const complete={id:'1',project_milestone_id:'m1',status:'completed',student_notes:null,completed_at:'now',project_milestones:{id:'m1',title:'One',description:'',instructions:'',sort_order:1,required:true,estimated_minutes:10,related_content_node_id:null}};
const pending={...complete,id:'2',project_milestone_id:'m2',status:'in_progress',completed_at:null,project_milestones:{...complete.project_milestones,id:'m2',sort_order:2}};
assert.deepEqual(milestoneProgress([complete,pending]),{completed:1,total:2,percent:50},'progress derives from required milestone completion');
assert.equal(canSubmit([complete,pending]),false);assert.equal(canSubmit([complete,{...pending,status:'completed'}]),true);
assert.match(migration,/p\.status='published'/,'draft and archived projects cannot start');
assert.match(migration,/owns_student\(sp\.student_id\)/,'student instance mutations enforce ownership');
assert.match(migration,/teacher_can_view_student\(sp\.student_id\)/,'teacher reviews enforce authorized student scope');
assert.match(migration,/sp\.school_id=current_school_id\(\)/,'admin reads remain tenant scoped');
assert.match(migration,/Complete required milestones before submission/,'project prerequisites are server enforced');
assert.match(migration,/evidence_weight[\s\S]*<=\.5/,'project evidence has moderate configurable weight');
assert.match(migration,/num_nonnulls\(class_id,student_id\)=1/,'assignments target exactly one student or class');
assert.match(migration,/status='completed'[\s\S]*student_reflection/,'completed project state retains portfolio reflection');
assert.match(migration,/mentorPolicy[\s\S]*Never produce the complete project/,'Nuru project mentor guides instead of completing work');
assert.match(edge,/nuru_build_project_context/,'project identifier selects trusted project context');
assert.match(routes,/path="skills\/:pathwayId"/);assert.match(routes,/path="project\/:studentProjectId"/);assert.match(routes,/path="portfolio"/);assert.match(routes,/path="projects" element={<TeacherProjectsPage/);
console.log('Stage 10 Skills Lab: all behavior and security contracts passed.');
