import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const sql=readFileSync('supabase/migrations/202609040004_stage11_intelligence_schedule.sql','utf8');
const app=readFileSync('src/App.tsx','utf8');
const edge=readFileSync('supabase/functions/nuru-tutor/index.ts','utf8');
for(const contract of ['teacher_class_intelligence','student_daily_plan','school_intelligence','configure_grade_learning','save_exam_mode','record_learning_intervention'])assert.match(sql,new RegExp(contract));
for(const table of ['grade_learning_settings','exam_modes','learning_interventions'])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));
assert.match(sql,/teacher_classes tc where tc\.teacher_id=teacher\.id and tc\.class_id=requested_class/);
assert.match(sql,/evidence_count>=cfg\.minimum_evidence and sm\.confidence_score>=40/);
assert.match(sql,/completionPercent.*understandingPercent/s);
assert.match(sql,/status='published'.*approved_at is not null/s);
assert.match(sql,/current_profile_role\(\)<>'school_admin'/);
assert.match(sql,/case when exists\(select 1 from active_exam\).*100 else 80/);
assert.match(sql,/then 30 else 50/);
assert.match(edge,/student_daily_plan/);
assert.match(edge,/slice\(0,3\)/);
for(const route of ['path="schedule" element={<StudentSchedule','classes/:classId/insights'])assert.ok(app.includes(route));
const eligible=x=>x.evidence>=3&&x.confidence>=40&&x.mastery<60&&x.recentCorrect/x.recentAttempts<.67;
assert.equal(eligible({evidence:1,confidence:20,mastery:20,recentCorrect:0,recentAttempts:1}),false);
assert.equal(eligible({evidence:6,confidence:80,mastery:43,recentCorrect:1,recentAttempts:5}),true);
assert.equal(eligible({evidence:10,confidence:90,mastery:55,recentCorrect:4,recentAttempts:5}),false);
assert.deepEqual({completion:90,understanding:55},{completion:90,understanding:55});
console.log('Stage 11 intelligence, authorization, evidence and scheduling contracts PASS');
