import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {recommend,validateGraph} from '../src/services/recommendationEngine.ts';
const course=(id,extra={})=>({id,targetType:'course',title:id,status:'published',enabled:true,...extra});
const base={grade:7,completedIds:new Set(['html','css']),strongSkillIds:new Set(),interestKeys:new Set(['ai']),feedback:[],popularTargetIds:new Set(),candidates:[]};
const candidates=[course('completed'),course('draft',{status:'draft'}),course('disabled',{enabled:false}),course('missing-prereq',{prerequisiteIds:['python']}),course('responsive',{relationship:'next_level',relationshipSourceIds:['css'],pathwayTitle:'Web Creator'}),course('ai-explorer',{interestKeys:['ai']}),{...course('portfolio',{prerequisiteIds:['html','css']}),targetType:'project'},course('teacher',{teacherName:'Ms. Wanjiku'}),{...course('practice',{practiceReason:'Recent practice suggests this skill could use more practice.'}),targetType:'skill'}];
base.completedIds.add('completed');
let result=recommend({...base,candidates});
for(const excluded of ['completed','draft','disabled','missing-prereq'])assert.ok(!result.some(x=>x.targetId===excluded),`${excluded} should be excluded`);
assert.ok(result.findIndex(x=>x.targetId==='responsive')<result.findIndex(x=>x.targetId==='ai-explorer'),'direct next level ranks above interest-only');
assert.equal(result.find(x=>x.targetId==='responsive').reasonCode,'next_level');
assert.equal(result.find(x=>x.targetId==='ai-explorer').reasonCode,'explicit_interest');
assert.equal(result.find(x=>x.targetId==='portfolio').reasonCode,'prerequisites_satisfied');
assert.equal(result.find(x=>x.targetId==='teacher').reasonText,'Recommended by Ms. Wanjiku.');
assert.equal(result.find(x=>x.targetId==='practice').category,'learning');assert.ok(result.filter(x=>x.category==='exploration').length>0);
result=recommend({...base,candidates,feedback:[{targetId:'ai-explorer',type:'not_interested'}]});assert.ok(!result.some(x=>x.targetId==='ai-explorer'),'dismissal strongly suppresses recommendation');
assert.ok(!recommend({...base,completedIds:new Set(['html']),candidates:[candidates[6]]}).length,'project requires all prerequisites');assert.ok(recommend({...base,candidates:[candidates[6]]}).length,'project eligible after prerequisites');
assert.deepEqual(validateGraph([{id:'a',status:'published'},{id:'b',status:'published'}],[{sourceId:'a',targetId:'b',type:'prerequisite',required:true},{sourceId:'b',targetId:'a',type:'prerequisite',required:true}]),['Circular prerequisite detected.']);
assert.ok(validateGraph([{id:'a',status:'published'}],[{sourceId:'a',targetId:'a',type:'prerequisite',required:true}]).includes('Self-reference is not allowed.'));
assert.ok(validateGraph([{id:'a',status:'published'}],[{sourceId:'a',targetId:'missing',type:'related'}]).includes('Relationship contains a missing target.'));
assert.ok(validateGraph([{id:'a',status:'published'},{id:'b',status:'archived'}],[{sourceId:'a',targetId:'b',type:'prerequisite',required:true}]).some(x=>x.includes('archived')));
const hardening=readFileSync(new URL('../supabase/migrations/202609040001_stage8_recommendation_availability.sql',import.meta.url),'utf8');
assert.match(hardening,/student_target_is_available\(me\.id,r\.target_id,r\.target_type\)/,'stored recommendations are re-authorized at read time');
assert.match(hardening,/school_pathway_settings x[\s\S]*x\.enabled/,'disabled school pathways are rejected server-side');
assert.match(hardening,/relationship_type='prerequisite'[\s\S]*event_type='course_completed'/,'project prerequisites are checked against completion evidence');
assert.match(hardening,/if not student_target_is_available\(requested_student,requested_target,kind\)/,'teacher recommendations cannot bypass availability');
assert.match(hardening,/left join content_nodes n on r\.target_type in \('content_node','project'\)/,'project metadata is resolved instead of returning a null target');
console.log('Stage 8 RecommendationEngine: all behavioral cases passed.');
