import {useState,type FormEvent} from 'react';
import {Link,Navigate,useNavigate} from 'react-router-dom';
import {BookOpen,ArrowLeft} from 'lucide-react';
import {useAuth} from '@/auth/AuthContext';
import {roleHome} from '@/auth/Routes';
import {authService} from '@/services/authService';

function Frame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="min-h-screen bg-ink-50 grid lg:grid-cols-2"><section className="hidden lg:flex bg-brand-900 text-white p-14 flex-col justify-between"><Link to="/" className="flex items-center gap-2 font-display text-xl font-bold"><BookOpen/>Learnova</Link><div><p className="text-brand-200 font-semibold">A focused learning workspace</p><h2 className="mt-3 max-w-lg font-display text-4xl font-bold leading-tight">Secure school communities, built around every learner.</h2></div><p className="text-brand-200 text-sm">Protected by school-level access controls.</p></section><section className="grid place-items-center p-6"><div className="w-full max-w-md"><Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-ink-600"><ArrowLeft size={16}/>Back to Learnova</Link><h1 className="text-heading text-3xl font-bold">{title}</h1><p className="text-body mt-2 mb-8">{subtitle}</p>{children}</div></section></main>}
const field='w-full rounded-xl border border-ink-300 bg-white px-4 py-3 text-sm focus:border-brand-500';
export function LoginPage(){const {signIn,role,configured}=useAuth();const nav=useNavigate();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(role)return <Navigate to={roleHome[role]} replace/>;async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);nav('/auth')}catch(x){setError(x instanceof Error?x.message:'Sign in failed')}finally{setBusy(false)}}return <Frame title="Welcome back" subtitle="Sign in with your school or Learnova account.">{!configured&&<p className="mb-4 rounded-xl bg-accent-50 p-3 text-sm text-accent-800">Supabase is not configured. Add the variables from .env.example.</p>}<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-semibold">Email<input className={`${field} mt-2`} type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm font-semibold">Password<input className={`${field} mt-2`} type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="text-sm text-red-700">{error}</p>}<button disabled={busy||!configured} className="w-full rounded-xl bg-brand-700 py-3 font-semibold text-white disabled:opacity-50">{busy?'Signing in…':'Sign in'}</button><Link className="block text-center text-sm font-semibold text-brand-700" to="/forgot-password">Forgot password?</Link></form></Frame>}
export function ForgotPasswordPage(){const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error:requestError}=await authService.resetPassword(email);if(requestError)throw requestError;setSent(true)}catch{setError('We could not send the reset email. Please wait a moment and try again.')}finally{setBusy(false)}}return <Frame title="Reset your password" subtitle="We’ll send a secure reset link to your email.">{sent?<p className="surface p-5" role="status">If an account exists for that address, check its inbox for a reset link.</p>:<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-semibold">Email<input className={`${field} mt-2`} type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-brand-700 py-3 font-semibold text-white disabled:opacity-50">{busy?'Sending…':'Send reset link'}</button></form>}</Frame>}
export function ResetPasswordPage(){const [password,setPassword]=useState(''),[done,setDone]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error:updateError}=await authService.updatePassword(password);if(updateError)throw updateError;setDone(true)}catch{setError('We could not update your password. Request a new reset link and try again.')}finally{setBusy(false)}}return <Frame title="Choose a new password" subtitle="Use at least eight characters and keep it private.">{done?<Link className="text-brand-700 font-semibold" to="/login">Password updated. Return to sign in →</Link>:<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-semibold">New password<input className={`${field} mt-2`} type="password" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-brand-700 py-3 font-semibold text-white disabled:opacity-50">{busy?'Updating…':'Update password'}</button></form>}</Frame>}
