import { ArrowRight, BookOpen, CheckCircle2, Clock3, Code2, Flame, Target, TrendingUp } from 'lucide-react';
import { studentDemoData } from '../data';
import { useDemo } from '../DemoContext';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { Badge } from '@/components/ui/Badge';
import { Reveal } from '@/components/ui/Reveal';

export function StudentHomeView() {
  const { setStage, setLessonMode } = useDemo();
  return <div><Reveal><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-eyebrow">Student Home</p><h2 className="text-heading mt-2 text-3xl font-bold sm:text-4xl">Good afternoon, Amani</h2><p className="text-body mt-2">Let's continue where you left off.</p></div><Badge variant="accent"><Flame className="h-3.5 w-3.5" />{studentDemoData.streak} day streak</Badge></div></Reveal>
    <Reveal delay={80} className="mt-7"><div className="surface overflow-hidden p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Target className="h-4 w-4" /></span><p className="font-display font-bold text-ink-900">Today's learning goal</p></div><p className="mt-3 text-sm text-ink-500">{studentDemoData.completedThisWeek} of {studentDemoData.weeklyGoal} weekly minutes completed</p></div><div className="text-left sm:text-right"><p className="font-display text-3xl font-extrabold text-brand-700">30 <span className="text-sm font-semibold text-ink-500">min recommended today</span></p><p className="mt-1 text-xs font-semibold text-brand-600">18 minutes completed today</p></div></div><ProgressBar value={60} className="mt-5" label="Today's progress" /></div></Reveal>
    <div className="mt-5 grid gap-5 lg:grid-cols-3"><Reveal className="lg:col-span-2"><div className="surface h-full p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><BookOpen className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-600">Continue learning</p><h3 className="font-display text-lg font-bold text-ink-900">Mathematics</h3></div></div><Badge variant="brand">72% topic progress</Badge></div><div className="mt-6 rounded-xl bg-ink-50 p-4"><p className="text-sm font-semibold text-ink-800">Algebra — Linear Equations</p><p className="mt-1 text-sm text-ink-500">Pick up from your last lesson and work through the next example.</p><ProgressBar value={72} size="sm" className="mt-4" /><button onClick={() => { setLessonMode('lesson'); setStage('learning'); }} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-700">Continue lesson <ArrowRight className="h-4 w-4" /></button></div></div></Reveal><Reveal delay={100}><div className="surface h-full p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-50 text-accent-600"><Target className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-wide text-accent-600">Recommended practice</p><h3 className="font-display text-base font-bold text-ink-900">Algebraic Word Problems</h3></div></div><p className="mt-5 text-sm text-ink-500">This is currently your weakest Algebra skill.</p><div className="mt-5 rounded-xl border border-orange-200 bg-orange-50 p-3"><p className="text-xs font-semibold text-orange-800">A focused 15-minute practice set is ready.</p></div><button onClick={() => { setLessonMode('practice'); setStage('learning'); }} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-600 hover:text-brand-700">Practice now <ArrowRight className="h-4 w-4" /></button></div></Reveal></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3"><Reveal className="lg:col-span-2"><div className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-50 text-accent-600"><Code2 className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-wide text-accent-600">Skills Lab</p><h3 className="font-display text-lg font-bold text-ink-900">Web Creator</h3></div></div><Badge variant="accent">38%</Badge></div><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-ink-800">Current module: CSS Foundations</p><p className="mt-1 text-sm text-ink-500">Next: make your homepage feel like yours.</p></div><ProgressBar value={38} size="sm" className="w-full sm:w-40" /></div><button onClick={() => setStage('skills')} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-ink-300 px-4 py-2.5 text-sm font-semibold text-ink-700 hover:bg-ink-50">Continue project pathway <ArrowRight className="h-4 w-4" /></button></div></Reveal><Reveal delay={100}><div className="surface p-5 sm:p-6"><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-brand-600" /><h3 className="font-display font-bold text-ink-900">Weekly activity</h3></div><div className="mt-5 flex h-28 items-end gap-2">{studentDemoData.activity.map((item) => <div key={item.day} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-20 w-full items-end"><div className={`w-full rounded-t-md ${item.minutes === 0 ? 'bg-ink-200' : 'bg-brand-500'}`} style={{ height: `${Math.max(item.minutes * 2, 5)}%` }} /></div><span className="text-[10px] font-semibold text-ink-400">{item.day}</span></div>)}</div><div className="mt-2 flex items-center gap-2 text-xs font-semibold text-accent-700"><Flame className="h-3.5 w-3.5" />6 day streak</div></div></Reveal></div>
    <Reveal delay={150} className="mt-5"><div className="surface p-5 sm:p-6"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-600" /><h3 className="font-display font-bold text-ink-900">Your progress</h3></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{studentDemoData.subjects.map((subject) => <div key={subject.name}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-ink-700">{subject.name}</span><span className="font-bold text-ink-800">{subject.progress}%</span></div><ProgressBar value={subject.progress} size="sm" /></div>)}</div><div className="mt-4 flex items-center gap-2 text-xs text-ink-500"><Clock3 className="h-3.5 w-3.5" />You have completed 112 minutes toward your weekly goal.</div></div></Reveal>
  </div>;
}
