import {useEffect,useState} from 'react';
import {PageHeader,EmptyState,Placeholder} from '@/layouts/AppShell';
import {useAuth} from '@/auth/AuthContext';
import {academicService} from '@/services/academicService';
import {peopleService} from '@/services/peopleService';
import type {SchoolClass,StudentProfile} from '@/types';
import {useNavigate} from 'react-router-dom';

export function StudentHome(){const {profile}=useAuth();const [student,setStudent]=useState<StudentProfile|null>(null),[nuru,setNuru]=useState(false);useEffect(()=>{peopleService.students().then(x=>setStudent(x[0]??null)).catch(()=>setStudent(null))},[]);return <><PageHeader eyebrow="Your learning" title={`Good afternoon, ${profile?.first_name??'learner'}`} description={student?.grades?.name??'Your grade will appear after school setup.'}/><EmptyState title="No learning activities have been assigned yet." body="When your teachers enable learning content, your lessons and practice will appear here."/><div className="fixed bottom-6 right-6 z-20 flex items-end gap-3">{nuru&&<div className="surface max-w-xs p-4 text-sm">Nuru will be available inside your lessons once learning content has been enabled.</div>}<button onClick={()=>setNuru(!nuru)} className="rounded-full bg-brand-700 p-4 text-white shadow-lift" aria-label="Need help?">✨<span className="sr-only">Need help?</span></button><span className="absolute -top-7 right-0 whitespace-nowrap rounded-full bg-white px-3 py-1 text-xs shadow">Need help?</span></div></>}
export function TeacherOverview(){const {school}=useAuth();const [classes,setClasses]=useState<SchoolClass[]>([]);useEffect(()=>{academicService.classes().then(setClasses).catch(()=>setClasses([]))},[]);return <><PageHeader eyebrow={school?.name} title="Teacher overview" description="Your assigned classes and learners, from live school data."/>{classes.length?<div className="grid gap-4 md:grid-cols-2">{classes.map(c=><article className="surface p-5" key={c.id}><h2 className="font-display font-bold">{c.name}</h2><p className="text-body mt-1 text-sm">{c.student_profiles?.[0]?.count??0} students</p></article>)}</div>:<EmptyState title="No classes assigned" body="Your school administrator can assign you to a class."/>}</>}
export function SchoolOverview(){const {school}=useAuth();const navigate=useNavigate();useEffect(()=>{academicService.settings().then(s=>{if(s&&!s.onboarding_completed)navigate('/school/onboarding',{replace:true})}).catch(()=>{})},[navigate]);return <><PageHeader eyebrow="School workspace" title={school?.name??'School overview'} description="Set up your academic structure and invite your school community."/><div className="grid gap-4 md:grid-cols-3">{['Students','Teachers','Classes'].map(x=><div className="surface p-6" key={x}><p className="text-sm font-semibold text-ink-500">{x}</p><p className="mt-3 text-sm text-ink-600">Open {x.toLowerCase()} to view live records.</p></div>)}</div></>}
export {Placeholder};
