import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {OpenAITutorProvider,type StructuredTutorResponse} from './provider.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const allowed=new Set(['explain','simplify','example','hint','mistake','practice','recommendation','compare','question']);
const respond=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json'}});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('authorization');if(!auth)return respond({error:'Authentication required'},401);
 const client=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{authorization:auth}}});
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 const body=await req.json();const question=String(body.question??'').trim();const interactionType=String(body.interactionType??'question');if(!question||question.length>600||!allowed.has(interactionType))return respond({error:'Invalid tutor request'},400);
 const contextCall=body.studentProjectId?client.rpc('nuru_build_project_context',{requested_student_project:body.studentProjectId}):client.rpc('nuru_build_context',{requested_course:body.courseId??null,requested_node:body.contentNodeId??null,requested_attempt:body.assessmentAttemptId??null,requested_question:body.questionId??null,requested_recommendation:body.recommendationTargetId??null});const {data:context,error}=await contextCall;if(error||!context)return respond({error:error?.message??'Approved learning context unavailable'},403);
 const studentId=context.student.id,schoolId=context.school.id,settings=context.settings;const since=new Date(Date.now()-600000).toISOString();const {count}=await admin.from('nuru_interactions').select('id',{count:'exact',head:true}).eq('student_id',studentId).gte('created_at',since);if((count??0)>=settings.requests_per_ten_minutes)return respond({error:'Rate limit reached'},429);
 let chosen=interactionType,restricted=false;const mode=context.mode as string,assessment=context.assessment;if(mode==='assessment'&&['example','practice','mistake'].includes(chosen)){chosen='hint';restricted=true}if(mode==='assessment'&&chosen==='hint'&&!assessment?.hintsAllowed)return respond({interactionId:crypto.randomUUID(),type:'clarifying_question',title:'Assessment help is limited',content:'I can clarify the wording, but hints are disabled for this assessment.',followUps:['Clarify the wording'],mode,restricted:true},200);if(mode==='practice'&&!context.currentQuestion?.attempted&&['mistake','example'].includes(chosen)){chosen='hint';restricted=true}
 const level=Math.min(Math.max(Number(body.hintLevel??1),1),assessment?.maximumHintLevel??3);const provider=new OpenAITutorProvider(Deno.env.get('OPENAI_API_KEY')!);let result:StructuredTutorResponse;const c=JSON.parse(JSON.stringify(context));
 if(chosen==='simplify')result=await provider.simplifyExplanation(c,question);else if(chosen==='example')result=await provider.giveExample(c,question);else if(chosen==='hint')result=await provider.giveHint(c,question,level);else if(chosen==='mistake')result=await provider.explainMistake(c,question);else if(chosen==='practice')result=await provider.generatePracticeExample(c,question);else if(chosen==='recommendation'||chosen==='compare')result=await provider.explainRecommendation(c,question);else if(chosen==='explain')result=await provider.explainConcept(c,question);else result=await provider.answerLearningQuestion(c,question);
 const validTypes=new Set(['explanation','hint','worked_example','mistake_explanation','concept_connection','practice_prompt','recommendation_explanation','clarifying_question']);result.type=validTypes.has(result.type)?result.type:'explanation';result.title=String(result.title??'Nuru explanation').slice(0,100);result.content=String(result.content??'').slice(0,1200);result.followUps=Array.isArray(result.followUps)?result.followUps.filter(x=>typeof x==='string').slice(0,3):[];if(mode==='assessment')delete result.temporaryPractice;
 const {data:log,error:logError}=await admin.from('nuru_interactions').insert({school_id:schoolId,student_id:studentId,course_id:context.currentCourse?.id??null,content_node_id:context.currentLesson?.id??null,assessment_attempt_id:assessment?.id??null,interaction_type:interactionType,mode,hint_level:chosen==='hint'?level:0,student_question:question,response_summary:result.content,provider:'openai',model:Deno.env.get('NURU_AI_MODEL')??'gpt-4o-mini'}).select('id').single();if(logError)throw logError;
 return respond({...result,interactionId:log.id,mode,hintLevel:chosen==='hint'?level:undefined,restricted});
 }catch(error){console.error('Nuru tutor failed',error instanceof Error?error.message:'unknown');return respond({error:'Nuru could not respond right now. Your lesson is still available.'},503)}});
