import { Check, ChevronLeft, ChevronRight } from 'lucide-react';
import type { DemoStage } from '../types';

export const demoStages: { id: DemoStage; label: string }[] = [
  { id: 'student', label: 'Student Home' }, { id: 'learning', label: 'Learning' }, { id: 'nuru', label: 'Nuru' }, { id: 'skills', label: 'Skills Lab' }, { id: 'teacher', label: 'Teacher Insights' }, { id: 'admin', label: 'School Admin' },
];

export function DemoProgress({ stage, onStage, onNext, onPrevious }: { stage: DemoStage; onStage: (stage: DemoStage) => void; onNext: () => void; onPrevious: () => void }) {
  const current = demoStages.findIndex((item) => item.id === stage);
  return <div className="border-b border-ink-200 bg-white px-4 py-3 lg:px-6"><div className="mx-auto flex max-w-7xl items-center gap-3"><div className="hidden items-center gap-1.5 lg:flex">{demoStages.map((item, index) => <button key={item.id} onClick={() => onStage(item.id)} className={`group flex items-center gap-2 rounded-lg px-2.5 py-2 text-xs font-semibold transition-colors ${stage === item.id ? 'bg-brand-50 text-brand-700' : 'text-ink-400 hover:bg-ink-50 hover:text-ink-700'}`}><span className={`flex h-5 w-5 items-center justify-center rounded-full text-[10px] ${index < current ? 'bg-brand-100 text-brand-700' : stage === item.id ? 'bg-brand-600 text-white' : 'bg-ink-100 text-ink-400'}`}>{index < current ? <Check className="h-3 w-3" /> : index + 1}</span>{item.label}</button>)}</div><label className="flex flex-1 items-center gap-2 lg:hidden"><span className="text-xs font-semibold text-ink-500">Demo step</span><select value={stage} onChange={(e) => onStage(e.target.value as DemoStage)} className="min-w-0 flex-1 rounded-lg border border-ink-200 bg-ink-50 px-3 py-2 text-sm font-semibold text-ink-800"><option value="student">Student Home</option><option value="learning">Smart Learning</option><option value="nuru">Nuru Assistance</option><option value="skills">Skills Lab</option><option value="teacher">Teacher Insights</option><option value="admin">School Admin</option></select></label><div className="ml-auto flex shrink-0 items-center gap-1"><button onClick={onPrevious} disabled={current <= 0} aria-label="Previous step" className="flex h-8 w-8 items-center justify-center rounded-lg text-ink-500 hover:bg-ink-100 disabled:opacity-30"><ChevronLeft className="h-4 w-4" /></button><button onClick={onNext} disabled={current >= demoStages.length - 1} aria-label="Next step" className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white hover:bg-brand-700 disabled:opacity-30"><ChevronRight className="h-4 w-4" /></button></div></div></div>;
}
