import { BarChart3, BookOpen, CalendarDays, FileText, GraduationCap, LayoutDashboard, Settings, Users, X } from 'lucide-react';
import type { DemoRole } from '../types';

const teacherLinks = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Classes', icon: GraduationCap }, { label: 'Students', icon: Users }, { label: 'Assignments', icon: FileText }, { label: 'Insights', icon: BarChart3 }];
const adminLinks = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Students', icon: Users }, { label: 'Classes', icon: GraduationCap }, { label: 'Learning Programs', icon: BookOpen }, { label: 'Schedule', icon: CalendarDays }, { label: 'Content', icon: FileText }, { label: 'Analytics', icon: BarChart3 }, { label: 'Settings', icon: Settings }];

export function RoleSidebar({ role, open, onClose }: { role: DemoRole; open: boolean; onClose: () => void }) {
  const isTeacher = role === 'teacher';
  const links = isTeacher ? teacherLinks : adminLinks;
  return <><div className={`fixed inset-0 z-40 bg-ink-950/30 lg:hidden ${open ? 'block' : 'hidden'}`} onClick={onClose} /><aside className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r border-ink-200 bg-white transition-transform duration-300 lg:static lg:z-auto lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-16 items-center justify-between border-b border-ink-100 px-5"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white"><span className="text-sm font-bold">L</span></span><span className="font-display font-bold text-ink-900">Learnova</span></div><button onClick={onClose} className="rounded-lg p-2 text-ink-400 hover:bg-ink-100 lg:hidden" aria-label="Close navigation"><X className="h-4 w-4" /></button></div><div className="px-3 py-5"><p className="px-3 text-[10px] font-bold uppercase tracking-wider text-ink-400">{isTeacher ? 'Teacher workspace' : 'Admin workspace'}</p><nav className="mt-3 space-y-1">{links.map((link, index) => <button key={link.label} onClick={onClose} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition-colors ${index === 0 ? 'bg-brand-50 text-brand-700' : 'text-ink-600 hover:bg-ink-50 hover:text-ink-900'}`}><link.icon className="h-4 w-4" />{link.label}</button>)}</nav></div><div className="mt-auto border-t border-ink-100 p-4"><div className="rounded-xl bg-ink-50 p-3"><p className="text-xs font-semibold text-ink-500">{isTeacher ? 'Demo Teacher' : 'Demo Account'}</p><p className="mt-1 text-sm font-bold text-ink-800">{isTeacher ? 'Ms. Wanjiku' : 'Peter Mwangi'}</p><p className="text-xs text-ink-500">Greenfield Academy</p></div></div></aside></>;
}
