import { Link } from 'react-router-dom';
import { BookOpen, ChartNoAxesCombined, Home, PencilRuler, Sparkles, X } from 'lucide-react';
import { studentDemoData } from '../data';
import type { DemoStage } from '../types';

const links = [{ label: 'Home', icon: Home, stage: 'student' as DemoStage }, { label: 'Learn', icon: BookOpen, stage: 'learning' as DemoStage }, { label: 'Practice', icon: PencilRuler, stage: 'learning' as DemoStage }, { label: 'Skills Lab', icon: Sparkles, stage: 'skills' as DemoStage }, { label: 'Progress', icon: ChartNoAxesCombined, stage: 'student' as DemoStage }];

export function StudentSidebar({ stage, onStage, open, onClose }: { stage: DemoStage; onStage: (stage: DemoStage) => void; open: boolean; onClose: () => void }) {
  return <><div className={`fixed inset-0 z-40 bg-ink-950/30 lg:hidden ${open ? 'block' : 'hidden'}`} onClick={onClose} /><aside className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r border-ink-200 bg-white transition-transform duration-300 lg:static lg:z-auto lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-16 items-center justify-between border-b border-ink-100 px-5"><Link to="/" className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white"><Sparkles className="h-4 w-4" /></span><span className="font-display font-bold text-ink-900">Learnova</span></Link><button onClick={onClose} className="rounded-lg p-2 text-ink-400 hover:bg-ink-100 lg:hidden" aria-label="Close navigation"><X className="h-4 w-4" /></button></div><div className="px-3 py-5"><p className="px-3 text-[10px] font-bold uppercase tracking-wider text-ink-400">Student workspace</p><nav className="mt-3 space-y-1">{links.map((link) => <button key={link.label} onClick={() => { onStage(link.stage); onClose(); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition-colors ${stage === link.stage || (link.label === 'Practice' && stage === 'learning') ? 'bg-brand-50 text-brand-700' : 'text-ink-600 hover:bg-ink-50 hover:text-ink-900'}`}><link.icon className="h-4 w-4" />{link.label}</button>)}</nav></div><div className="mt-auto border-t border-ink-100 p-4"><div className="rounded-xl bg-ink-50 p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-100 text-sm font-bold text-brand-700">AN</div><div className="min-w-0"><p className="truncate text-sm font-bold text-ink-800">{studentDemoData.name}</p><p className="text-xs text-ink-500">{studentDemoData.grade}</p></div></div><div className="mt-3 flex items-center justify-between text-[10px] font-semibold"><span className="text-ink-500">{studentDemoData.school}</span><span className="rounded-full bg-accent-100 px-2 py-0.5 text-accent-700">Demo Account</span></div></div></div></aside></>;
}
