-- Stage 8: governed skill graph, pathways, interests and explainable recommendations.
create type public.graph_entity_type as enum ('course','skill','content_node','pathway','level','project');
create type public.graph_relationship_type as enum ('prerequisite','recommended_after','next_level','related','supports_skill','builds_on','alternative_path','applies_skill','leads_to_project');
create table public.learning_pathways(id uuid primary key default gen_random_uuid(),scope content_scope not null,school_id uuid references schools(id) on delete cascade,title text not null,description text not null default '',category text not null check(category in('academic','skill','exploration')),difficulty text not null default 'introductory',minimum_grade integer,maximum_grade integer,status content_status not null default 'draft',created_by uuid not null references profiles(id),approved_by uuid references profiles(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((scope='global' and school_id is null) or(scope='school' and school_id is not null)),check(minimum_grade is null or maximum_grade is null or minimum_grade<=maximum_grade));
create table public.pathway_items(id uuid primary key default gen_random_uuid(),pathway_id uuid not null references learning_pathways(id) on delete cascade,course_id uuid references courses(id),skill_id uuid references skills(id),content_node_id uuid references content_nodes(id),level integer not null check(level>0),sort_order integer not null default 0,is_required boolean not null default true,created_at timestamptz not null default now(),check(num_nonnulls(course_id,skill_id,content_node_id)=1));
create table public.learning_graph_relationships(id uuid primary key default gen_random_uuid(),scope content_scope not null,school_id uuid references schools(id) on delete cascade,source_type graph_entity_type not null,source_id uuid not null,target_type graph_entity_type not null,target_id uuid not null,relationship_type graph_relationship_type not null,is_required boolean not null default false,weight integer not null default 1,created_by uuid not null references profiles(id),created_at timestamptz not null default now(),check(source_id<>target_id),check((scope='global' and school_id is null)or(scope='school' and school_id is not null)),unique(scope,school_id,source_type,source_id,target_type,target_id,relationship_type));
create table public.school_pathway_settings(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id) on delete cascade,pathway_id uuid not null references learning_pathways(id) on delete cascade,enabled boolean not null default false,minimum_grade integer,maximum_grade integer,requirement text not null default 'optional' check(requirement in('optional','required')),updated_at timestamptz not null default now(),unique(school_id,pathway_id));
create table public.student_pathway_progress(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id) on delete cascade,student_id uuid not null references student_profiles(id) on delete cascade,pathway_id uuid not null references learning_pathways(id) on delete cascade,current_level integer not null default 0,progress_percentage integer not null default 0 check(progress_percentage between 0 and 100),status text not null default 'not_started' check(status in('not_started','exploring','in_progress','completed')),started_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now(),unique(student_id,pathway_id));
create table public.student_interests(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id) on delete cascade,student_id uuid not null references student_profiles(id) on delete cascade,interest_key text not null,interest_label text not null,interest_category text not null,interest_level text not null check(interest_level in('curious','interested','very_interested')),source text not null default 'student_selected' check(source in('student_selected','exploration_behavior')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(student_id,interest_key));
create table public.student_recommendations(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id) on delete cascade,student_id uuid not null references student_profiles(id) on delete cascade,recommendation_type text not null check(recommendation_type in('practice','next_lesson','next_course','next_level','explore_pathway','project','teacher_recommended')),target_type graph_entity_type not null,target_id uuid not null,score integer not null,reason_code text not null,reason_text text not null,status text not null default 'active' check(status in('active','accepted','dismissed','completed','expired')),generated_by text not null check(generated_by in('rules_engine','teacher')),teacher_id uuid references teacher_profiles(id),created_at timestamptz not null default now(),expires_at timestamptz);
create table public.recommendation_feedback(id uuid primary key default gen_random_uuid(),recommendation_id uuid not null references student_recommendations(id) on delete cascade,student_id uuid not null references student_profiles(id) on delete cascade,feedback_type text not null check(feedback_type in('interested','not_interested','maybe_later','started','completed','shown','opened')),created_at timestamptz not null default now());
create table public.recommendation_events(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id) on delete cascade,recommendation_id uuid not null references student_recommendations(id) on delete cascade,event_type text not null check(event_type in('shown','opened','accepted','dismissed','started','completed')),created_at timestamptz not null default now());
create index recommendation_student_active on student_recommendations(student_id,status,score desc);create index interest_school_key on student_interests(school_id,interest_key);create index graph_source on learning_graph_relationships(source_id,relationship_type);create index graph_target on learning_graph_relationships(target_id,relationship_type);

create function public.validate_learning_graph() returns trigger language plpgsql security definer set search_path=public as $$begin
 if new.source_id=new.target_id then raise exception 'Self-reference is not allowed';end if;
 if new.relationship_type='prerequisite' and new.is_required and exists(with recursive walk(id) as(select new.target_id union select r.target_id from learning_graph_relationships r join walk w on r.source_id=w.id where r.relationship_type='prerequisite' and r.is_required)select 1 from walk where id=new.source_id) then raise exception 'Circular prerequisite detected.';end if;return new;end$$;
create trigger validate_graph before insert or update on learning_graph_relationships for each row execute function validate_learning_graph();

create function public.set_student_interest(requested_key text,requested_label text,requested_category text,requested_level text) returns student_interests language plpgsql security definer set search_path=public as $$declare me student_profiles;saved student_interests;begin select s.* into me from student_profiles s join profiles p on p.id=s.profile_id where p.user_id=auth.uid();if not found then raise exception 'Student required';end if;insert into student_interests(school_id,student_id,interest_key,interest_label,interest_category,interest_level)values(me.school_id,me.id,requested_key,requested_label,requested_category,requested_level)on conflict(student_id,interest_key)do update set interest_label=excluded.interest_label,interest_category=excluded.interest_category,interest_level=excluded.interest_level,source='student_selected',updated_at=now() returning * into saved;return saved;end$$;
create function public.configure_school_pathway(requested_pathway uuid,requested_enabled boolean,requested_minimum_grade integer,requested_maximum_grade integer,requested_requirement text) returns uuid language plpgsql security definer set search_path=public as $$declare result uuid;begin if current_profile_role()<>'school_admin' then raise exception 'School administrator required';end if;if not exists(select 1 from learning_pathways where id=requested_pathway and status='published' and scope='global')then raise exception 'Published global pathway required';end if;insert into school_pathway_settings(school_id,pathway_id,enabled,minimum_grade,maximum_grade,requirement)values(current_school_id(),requested_pathway,requested_enabled,requested_minimum_grade,requested_maximum_grade,requested_requirement)on conflict(school_id,pathway_id)do update set enabled=excluded.enabled,minimum_grade=excluded.minimum_grade,maximum_grade=excluded.maximum_grade,requirement=excluded.requirement,updated_at=now()returning id into result;return result;end$$;
create function public.teacher_recommend_learning(requested_student uuid,requested_target uuid,requested_target_type text,requested_note text default null)returns uuid language plpgsql security definer set search_path=public as $$declare teacher teacher_profiles;result uuid;begin select t.* into teacher from teacher_profiles t join profiles p on p.id=t.profile_id where p.user_id=auth.uid();if not found or not teacher_can_view_student(requested_student)then raise exception 'Student is outside your assigned classes';end if;insert into student_recommendations(school_id,student_id,recommendation_type,target_type,target_id,score,reason_code,reason_text,generated_by,teacher_id)values(teacher.school_id,requested_student,'teacher_recommended',requested_target_type::graph_entity_type,requested_target,35,'teacher_recommended','Recommended by '||(select first_name||' '||last_name from profiles where id=teacher.profile_id)||coalesce(': '||requested_note,''),'teacher',teacher.id)returning id into result;return result;end$$;
create function public.record_recommendation_feedback(requested_target uuid,requested_feedback text)returns uuid language plpgsql security definer set search_path=public as $$declare me student_profiles;r student_recommendations;result uuid;begin select s.* into me from student_profiles s join profiles p on p.id=s.profile_id where p.user_id=auth.uid();select * into r from student_recommendations where student_id=me.id and target_id=requested_target and status='active' order by created_at desc limit 1;if not found then raise exception 'Active recommendation not found';end if;insert into recommendation_feedback(recommendation_id,student_id,feedback_type)values(r.id,me.id,requested_feedback)returning id into result;if requested_feedback='not_interested'then update student_recommendations set status='dismissed' where id=r.id;elsif requested_feedback='interested'then update student_recommendations set status='accepted' where id=r.id;end if;return result;end$$;
-- Server-side generation uses stored graph edges. It separates Stage 7 practice from exploration and never invokes an LLM.
create function public.generate_student_recommendations()returns jsonb language sql security invoker set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('targetId',r.target_id,'targetType',r.target_type,'title',coalesce(c.title,p.title,s.name),'description',coalesce(c.description,p.description,''),'recommendationType',r.recommendation_type,'category',case when r.recommendation_type='practice'then'learning'else'exploration'end,'score',r.score,'reasonCode',r.reason_code,'reasonText',r.reason_text)order by r.score desc),'[]')from student_recommendations r join student_profiles me on me.id=r.student_id and owns_student(me.id)left join courses c on r.target_type='course'and c.id=r.target_id left join learning_pathways p on r.target_type='pathway'and p.id=r.target_id left join skills s on r.target_type='skill'and s.id=r.target_id where r.status='active'and(r.expires_at is null or r.expires_at>now())and coalesce(c.status,p.status,'published')='published'and not exists(select 1 from recommendation_feedback f where f.recommendation_id=r.id and f.feedback_type='not_interested')$$;

-- Tenant-scoped policies; student mutation is mediated by narrow RPCs.
do $$declare t text;begin foreach t in array array['learning_pathways','pathway_items','learning_graph_relationships','school_pathway_settings','student_pathway_progress','student_interests','student_recommendations','recommendation_feedback','recommendation_events']loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy pathways_read on learning_pathways for select using(scope='global'or school_id=current_school_id());create policy pathways_govern on learning_pathways for all using(is_platform_admin()or(scope='school'and school_id=current_school_id()and current_profile_role()='school_admin'))with check(is_platform_admin()or(scope='school'and school_id=current_school_id()and current_profile_role()='school_admin'));
create policy pathway_items_read on pathway_items for select using(exists(select 1 from learning_pathways p where p.id=pathway_id and(p.scope='global'or p.school_id=current_school_id())));create policy graph_read on learning_graph_relationships for select using(scope='global'or school_id=current_school_id());create policy graph_write on learning_graph_relationships for all using(is_platform_admin()or school_id=current_school_id()and current_profile_role()='school_admin')with check(is_platform_admin()or school_id=current_school_id()and current_profile_role()='school_admin');
create policy school_pathway_tenant on school_pathway_settings for select using(school_id=current_school_id()or is_platform_admin());create policy progress_pathway_read on student_pathway_progress for select using(owns_student(student_id)or school_id=current_school_id()and current_profile_role()in('teacher','school_admin'));create policy interests_own on student_interests for select using(owns_student(student_id));create policy interests_delete on student_interests for delete using(owns_student(student_id));create policy recommendations_access on student_recommendations for select using(owns_student(student_id)or teacher_can_view_student(student_id)or school_id=current_school_id()and current_profile_role()='school_admin');create policy feedback_own on recommendation_feedback for select using(owns_student(student_id));create policy events_school on recommendation_events for select using(school_id=current_school_id()and current_profile_role()='school_admin');
grant execute on function set_student_interest(text,text,text,text),configure_school_pathway(uuid,boolean,integer,integer,text),teacher_recommend_learning(uuid,uuid,text,text),record_recommendation_feedback(uuid,text),generate_student_recommendations()to authenticated;
comment on table recommendation_events is 'Aggregate school analytics only; never use this table for public student rankings.';

-- Progress is always derived from required pathway items and completed learning evidence.
create function public.refresh_student_pathway_progress(requested_pathway uuid) returns student_pathway_progress language plpgsql security definer set search_path=public as $$
declare me student_profiles;total integer;done integer;level_now integer;saved student_pathway_progress;
begin select s.* into me from student_profiles s join profiles p on p.id=s.profile_id where p.user_id=auth.uid();if not found then raise exception 'Student required';end if;
 if not exists(select 1 from school_pathway_settings x join learning_pathways p on p.id=x.pathway_id where x.school_id=me.school_id and x.pathway_id=requested_pathway and x.enabled and p.status='published')then raise exception 'Pathway is not available';end if;
 select count(*),count(*)filter(where (i.course_id is not null and exists(select 1 from learning_events e where e.student_id=me.id and e.course_id=i.course_id and e.event_type='course_completed'))or(i.content_node_id is not null and exists(select 1 from student_content_progress cp where cp.student_id=me.id and cp.content_node_id=i.content_node_id and cp.status='completed'))or(i.skill_id is not null and exists(select 1 from student_skill_mastery m where m.student_id=me.id and m.skill_id=i.skill_id and m.mastery_level in('on_track','strong')))),coalesce(max(i.level)filter(where (i.course_id is not null and exists(select 1 from learning_events e where e.student_id=me.id and e.course_id=i.course_id and e.event_type='course_completed'))or(i.content_node_id is not null and exists(select 1 from student_content_progress cp where cp.student_id=me.id and cp.content_node_id=i.content_node_id and cp.status='completed'))),0)into total,done,level_now from pathway_items i where i.pathway_id=requested_pathway and i.is_required;
 insert into student_pathway_progress(school_id,student_id,pathway_id,current_level,progress_percentage,status,started_at,completed_at)values(me.school_id,me.id,requested_pathway,level_now,case when total=0 then 0 else round(100.0*done/total)end,case when done=0 then'not_started'when done=total then'completed'else'in_progress'end,case when done>0 then now()end,case when done=total and total>0 then now()end)on conflict(student_id,pathway_id)do update set current_level=excluded.current_level,progress_percentage=excluded.progress_percentage,status=excluded.status,started_at=coalesce(student_pathway_progress.started_at,excluded.started_at),completed_at=excluded.completed_at,updated_at=now()returning * into saved;return saved;end$$;
grant execute on function refresh_student_pathway_progress(uuid)to authenticated;

-- Privacy-preserving opportunity signal: only groups of five or more are exposed.
create view public.school_interest_opportunities with(security_invoker=true)as select i.school_id,i.interest_key,max(i.interest_label)interest_label,count(distinct i.student_id)interested_students from student_interests i where i.source='student_selected' group by i.school_id,i.interest_key having count(distinct i.student_id)>=5;
comment on view school_interest_opportunities is 'School-admin input to human-authorized content opportunities; aggregated with a minimum cohort of five and never auto-generates content.';
