import {useState} from 'react';
import {NavLink,Outlet} from 'react-router-dom';
import {BookOpen,LogOut,Menu,X,type LucideIcon} from 'lucide-react';
import {useAuth} from '@/auth/AuthContext';
export interface NavItem{label:string;to:string;icon:LucideIcon}
export function AppShell({items,area}:{items:NavItem[];area:string}){const [open,setOpen]=useState(false);const {profile,school,signOut}=useAuth();return <div className="min-h-screen bg-ink-50"><button onClick={()=>setOpen(true)} className="fixed left-4 top-4 z-30 rounded-xl bg-white p-2 shadow lg:hidden" aria-label="Open navigation"><Menu/></button>{open&&<button className="fixed inset-0 z-30 bg-ink-950/30 lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}<aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col bg-brand-950 text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><NavLink to="/" className="flex items-center gap-2 font-display text-xl font-bold"><BookOpen className="text-brand-300"/>Learnova</NavLink><button onClick={()=>setOpen(false)} className="lg:hidden"><X/></button></div><div className="px-6 py-5"><p className="text-xs font-semibold uppercase tracking-wider text-brand-300">{area}</p><p className="mt-1 truncate font-semibold">{school?.name??'Learnova Platform'}</p></div><nav className="flex-1 space-y-1 px-3">{items.map(i=><NavLink key={i.to} to={i.to} end={i.to.split('/').length===2} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium ${isActive?'bg-white text-brand-950':'text-brand-100 hover:bg-white/10'}`}><i.icon size={19}/>{i.label}</NavLink>)}</nav><div className="border-t border-white/10 p-4"><p className="px-2 text-sm font-semibold">{profile?.display_name}</p><p className="px-2 text-xs text-brand-300">{profile?.role.replace('_',' ')}</p><button onClick={()=>void signOut()} className="mt-3 flex w-full items-center gap-2 rounded-xl px-3 py-2 text-sm hover:bg-white/10"><LogOut size={17}/>Sign out</button></div></aside><main className="min-h-screen lg:pl-72"><div className="mx-auto max-w-7xl px-5 pb-12 pt-20 lg:px-10 lg:pt-10"><Outlet/></div></main></div>}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:React.ReactNode}){return <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<p className="text-eyebrow">{eyebrow}</p>}<h1 className="text-heading text-3xl font-bold">{title}</h1>{description&&<p className="text-body mt-2">{description}</p>}</div>{action}</header>}
export function EmptyState({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="surface px-6 py-14 text-center"><BookOpen className="mx-auto text-brand-600"/><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><p className="text-body mx-auto mt-2 max-w-md text-sm">{body}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function Placeholder({title,stage}:{title:string;stage:string}){return <><PageHeader title={title}/><EmptyState title={`${title} is coming next`} body={`This workspace is reserved for ${stage}. No demo data is shown here.`}/></>}
