import {useEffect,useRef,useState,type ReactNode} from 'react';
import {BookOpen,CheckCircle2,ChevronDown,ChevronRight,Lightbulb,MessageSquareText,Sparkles} from 'lucide-react';
import type {LearningNode,NodeProgress} from '@/services/learningService';

export function ProgressMeter({value,label='Course progress'}:{value:number;label?:string}){return <div><div className="mb-1 flex justify-between text-xs font-semibold text-ink-600"><span>{label}</span><span>{value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-ink-200" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-brand-600 transition-all" style={{width:`${value}%`}}/></div></div>}
export function LoadState({loading,error,onRetry,children}:{loading:boolean;error:string|null;onRetry:()=>void;children:ReactNode}){if(loading)return <div className="surface p-8 text-center text-ink-600">Loading your learning space…</div>;if(error)return <div className="surface p-8 text-center"><p className="font-semibold">We couldn't load this right now.</p><p className="mt-1 text-sm text-ink-600">{error}</p><button className="mt-4 rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white" onClick={onRetry}>Retry</button></div>;return <>{children}</>}

type Block={id?:string;type:string;title?:string;text?:string;items?:string[];answer?:string;prompt?:string;src?:string;alt?:string};
export function ContentRenderer({node,onPosition,onActivity}:{node:LearningNode;onPosition:(id:string)=>void;onActivity:(id:string)=>Promise<void>}){
 const raw=Array.isArray(node.structured_content?.components)?node.structured_content.components as Block[]:[];
 const blocks=raw.length?raw:[{id:'lesson-content',type:'text',text:node.body||'Your school has not added lesson text yet.'}];
 return <div className="space-y-5">{blocks.map((b,i)=><ContentBlock key={b.id??i} block={b} id={b.id??`section-${i}`} onView={onPosition} onActivity={onActivity}/>)}</div>
}
function ContentBlock({block,id,onView,onActivity}:{block:Block;id:string;onView:(id:string)=>void;onActivity:(id:string)=>Promise<void>}){
 const ref=useRef<HTMLElement|null>(null);const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[reflection,setReflection]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)onView(id)},{threshold:.6});observer.observe(el);return()=>observer.disconnect()},[id,onView]);
 const activity=['activity','reflection'].includes(block.type);
 const complete=async()=>{await onActivity(id);setSaved(true)};
 let content:ReactNode;
 if(block.type==='heading')content=<h2 className="text-heading text-2xl font-bold">{block.text??block.title}</h2>;
 else if(block.type==='definition')content=<aside className="rounded-2xl border-l-4 border-brand-500 bg-brand-50 p-5"><p className="text-xs font-bold uppercase text-brand-700">Definition</p><p className="mt-2">{block.text}</p></aside>;
 else if(['example','worked_example'].includes(block.type))content=<aside className="rounded-2xl bg-amber-50 p-5"><p className="flex items-center gap-2 font-bold"><Lightbulb size={18}/>{block.title??(block.type==='worked_example'?'Worked example':'Example')}</p><p className="mt-2 whitespace-pre-line text-ink-700">{block.text}</p></aside>;
 else if(block.type==='callout')content=<aside className="rounded-2xl bg-sky-50 p-5 font-medium text-sky-950">{block.text}</aside>;
 else if(block.type==='image')content=<figure className="rounded-2xl border border-dashed border-ink-300 bg-ink-50 p-8 text-center"><BookOpen className="mx-auto text-ink-400"/><figcaption className="mt-2 text-sm text-ink-600">{block.alt??block.title??'Lesson image reference'}</figcaption></figure>;
 else if(block.type==='reflection')content=<div className="rounded-2xl border border-brand-200 p-5"><p className="font-bold">{block.prompt??block.title??'Pause and reflect'}</p><textarea value={reflection} onChange={e=>setReflection(e.target.value)} className="mt-3 min-h-28 w-full rounded-xl border border-ink-300 p-3" placeholder="Write your reflection…"/><button disabled={!reflection.trim()||saved} onClick={()=>void complete()} className="mt-3 rounded-lg bg-brand-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saved?'Reflection saved':'Save reflection'}</button></div>;
 else if(block.type==='activity')content=<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-bold">{block.prompt??block.title??'Quick activity'}</p>{block.items?.length?<div className="mt-3 space-y-2">{block.items.map(x=><label className="flex gap-2" key={x}><input type="radio" name={id} checked={selected===x} onChange={()=>setSelected(x)}/>{x}</label>)}</div>:null}{block.answer&&<><button onClick={()=>setOpen(!open)} className="mt-3 text-sm font-bold text-brand-700">{open?'Hide answer':'Reveal answer'}</button>{open&&<p className="mt-2 rounded-lg bg-white p-3 text-sm">{block.answer}</p>}</>}<button disabled={saved} onClick={()=>void complete()} className="mt-3 block rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saved?'Activity complete':'Mark complete'}</button></div>;
 else if(['practice_preview','project_instruction'].includes(block.type))content=<div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p className="font-bold">{block.title??(block.type==='project_instruction'?'Project milestone':'Try it yourself')}</p><p className="mt-2 whitespace-pre-line">{block.text}</p></div>;
 else if(block.type==='summary')content=<div className="rounded-2xl bg-brand-950 p-6 text-white"><p className="font-bold">Summary</p><p className="mt-2 text-brand-100">{block.text}</p></div>;
 else content=<p className="whitespace-pre-line leading-8 text-ink-700">{block.text}</p>;
 return <section ref={ref as React.RefObject<HTMLElement>} id={id} data-activity={activity}>{content}</section>
}
export function CourseTree({nodes,progress,currentId}:{nodes:LearningNode[];progress:NodeProgress[];currentId?:string}){return <ol className="space-y-2">{nodes.map(n=>{const status=progress.find(p=>p.content_node_id===n.id)?.status;return <li key={n.id} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-sm ${n.id===currentId?'bg-brand-100 font-bold text-brand-900':''}`}>{status==='completed'?<CheckCircle2 className="text-emerald-600" size={18}/>:n.id===currentId?<ChevronRight className="text-brand-600" size={18}/>:<span className="h-4 w-4 rounded-full border border-ink-300"/>}<span>{n.title}</span></li>})}</ol>}
export function NuruPlaceholder({courseId,contentNodeId,subject,topic}:{courseId:string;contentNodeId:string;subject?:string;topic:string}){const [open,setOpen]=useState(false);return <div className="fixed bottom-5 right-5 z-30">{open&&<div className="mb-3 w-72 rounded-2xl border bg-white p-5 shadow-lift"><div className="flex items-center gap-2 font-bold"><Sparkles className="text-brand-600"/>Nuru</div><p className="mt-3 text-sm text-ink-600">Nuru learning support will be available here soon.</p><p className="mt-3 truncate text-xs text-ink-400">{subject?`${subject} · `:''}{topic}</p><span className="sr-only">Context {courseId} {contentNodeId}</span></div>}<button onClick={()=>setOpen(!open)} className="ml-auto flex items-center gap-2 rounded-full bg-brand-700 px-4 py-3 font-semibold text-white shadow-lift" aria-expanded={open}><MessageSquareText size={20}/>Ask Nuru<ChevronDown size={16}/></button></div>}
