import {useMemo,useState} from 'react';
import {ChevronDown,MessageSquareText,RefreshCw,Send,Sparkles,ThumbsDown,ThumbsUp} from 'lucide-react';
import {tutorService} from '@/services/nuru/tutorService';
import type {NuruInteractionType,NuruRequest,NuruResponse} from '@/services/nuru/tutorTypes';

interface Props {courseId?:string;contentNodeId?:string;assessmentAttemptId?:string;questionId?:string;recommendationTargetId?:string;topic?:string;variant?:'learning'|'practice'|'explore';attempted?:boolean}
const actions:Record<string,[string,NuruInteractionType][]>={learning:[['Explain this more simply','simplify'],['Give me another example','example'],['Help me understand this step','explain'],['What should I review?','question']],practice:[['Give me a hint','hint'],['Why was my answer wrong?','mistake'],['Explain the method','explain']],explore:[['Help me choose','question'],['Why this pathway?','recommendation'],['What would I learn here?','question'],['Compare these two options','compare']]};
export function NuruLearningAssistant(props:Props){const [open,setOpen]=useState(false),[question,setQuestion]=useState(''),[response,setResponse]=useState<NuruResponse|null>(null),[state,setState]=useState<'idle'|'thinking'|'error'|'rate'|'offline'>('idle'),[hintLevel,setHintLevel]=useState(0),[rated,setRated]=useState(false);const quick=useMemo(()=>actions[props.variant??'learning'],[props.variant]);
 const ask=async(text:string,type:NuruInteractionType)=>{if(!text.trim()||state==='thinking')return;setOpen(false);setState('thinking');const nextHint=type==='hint'?hintLevel+1:hintLevel;const request:NuruRequest={question:text.trim(),interactionType:type,courseId:props.courseId,contentNodeId:props.contentNodeId,assessmentAttemptId:props.assessmentAttemptId,questionId:props.questionId,recommendationTargetId:props.recommendationTargetId,hintLevel:nextHint};try{const result=await tutorService.ask(request);setResponse(result);setHintLevel(result.hintLevel??nextHint);setState('idle');setRated(false)}catch(e){const message=e instanceof Error?e.message:'';setState(/429|rate/i.test(message)?'rate':navigator.onLine?'error':'offline')}};
 const submit=()=>{const value=question;setQuestion('');void ask(value,'question')};const vote=(rating:'helpful'|'not_helpful')=>{if(!response)return;setRated(true);void tutorService.feedback(response.interactionId,rating).catch(()=>setRated(false))};
 return <>{(state==='thinking'||response||state!=='idle')&&<section aria-live="polite" className="mt-7 rounded-2xl border border-brand-200 bg-brand-50 p-5 sm:p-6"><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-brand-700"><Sparkles size={17}/>Nuru {response?.type.replace(/_/g,' ')??'learning assistant'}</div>{state==='thinking'?<p className="mt-3 font-semibold">Thinking about your current learning…</p>:state!=='idle'?<><h2 className="mt-3 text-lg font-bold">Nuru couldn't respond right now</h2><p className="mt-1 text-sm text-ink-600">{state==='rate'?'You’ve reached the help limit for now. Please wait a moment.':state==='offline'?'Check your connection. Your lesson is still available.':'Your lesson is still available.'}</p><button onClick={()=>setOpen(true)} className="mt-3 flex items-center gap-2 text-sm font-bold text-brand-700"><RefreshCw size={15}/>Retry</button></>:response&&<><h2 className="mt-2 text-xl font-bold">{response.title}</h2><p className="mt-3 whitespace-pre-line leading-7 text-ink-700">{response.content}</p>{response.temporaryPractice&&<div className="mt-4 rounded-xl bg-white p-4"><span className="text-xs font-bold uppercase text-violet-700">Temporary AI practice</span><p className="mt-2 font-semibold">{response.temporaryPractice.prompt}</p></div>}<div className="mt-5 flex flex-wrap gap-2">{response.followUps.map(label=><button key={label} onClick={()=>void ask(label,/hint/i.test(label)?'hint':/example/i.test(label)?'example':'question')} className="rounded-lg border border-brand-300 bg-white px-3 py-2 text-sm font-bold text-brand-800">{label}</button>)}<button onClick={()=>setResponse(null)} className="px-3 py-2 text-sm font-bold text-ink-600">Back to {props.variant==='explore'?'explore':'lesson'}</button></div><div className="mt-4 flex gap-3 border-t border-brand-200 pt-3 text-xs text-ink-500"><span>Was this helpful?</span><button disabled={rated} aria-label="Helpful" onClick={()=>vote('helpful')}><ThumbsUp size={15}/></button><button disabled={rated} aria-label="Not helpful" onClick={()=>vote('not_helpful')}><ThumbsDown size={15}/></button>{rated&&<span>Thanks for your feedback.</span>}</div></>}</section>}
 <div className="fixed bottom-5 right-5 z-30">{open&&<div className="mb-3 w-[min(22rem,calc(100vw-2.5rem))] rounded-2xl border bg-white p-5 shadow-lift"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 font-bold"><Sparkles className="text-brand-600"/>Nuru</div><p className="text-xs text-ink-500">Learning assistant</p></div><button aria-label="Close Nuru" onClick={()=>setOpen(false)}><ChevronDown/></button></div>{props.topic&&<p className="mt-3 truncate text-xs font-semibold text-brand-700">Helping with {props.topic}</p>}<div className="mt-3 flex flex-wrap gap-2">{quick.filter(([label])=>props.attempted!==false||label!=='Why was my answer wrong?').map(([label,type])=><button key={label} onClick={()=>void ask(label,type)} className="rounded-full bg-brand-50 px-3 py-2 text-left text-xs font-semibold text-brand-800">{label}</button>)}</div><div className="mt-4 flex gap-2"><textarea maxLength={600} rows={2} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask something about what you're learning..." className="min-w-0 flex-1 resize-none rounded-xl border p-3 text-sm"/><button disabled={!question.trim()} onClick={submit} aria-label="Send to Nuru" className="self-end rounded-xl bg-brand-700 p-3 text-white disabled:opacity-40"><Send size={18}/></button></div><p className="mt-1 text-right text-[10px] text-ink-400">{question.length}/600</p></div>}<button onClick={()=>setOpen(!open)} className="ml-auto flex items-center gap-2 rounded-full bg-brand-700 px-4 py-3 font-semibold text-white shadow-lift" aria-expanded={open}><MessageSquareText size={20}/>{open?'Close':'Need help?'}</button></div></>}
